commerce_lakehouse:
  target: minio
  outputs:
    minio:
      type: spark
      method: session
      host: NA
      schema: gold
      threads: 1
      server_side_parameters:
        spark.sql.extensions: org.apache.iceberg.spark.extensions.IcebergSparkSessionExtensions
        spark.sql.defaultCatalog: minio_lake
        spark.sql.session.timeZone: UTC
        spark.sql.shuffle.partitions: '2'
        spark.sql.catalog.minio_lake: org.apache.iceberg.spark.SparkCatalog
        spark.sql.catalog.minio_lake.catalog-impl: org.apache.iceberg.jdbc.JdbcCatalog
        spark.sql.catalog.minio_lake.uri: jdbc:postgresql://postgres:5432/iceberg_catalog
        spark.sql.catalog.minio_lake.jdbc.user: commerce
        spark.sql.catalog.minio_lake.jdbc.password: "{{ env_var('DBT_ENV_SECRET_PG_PASSWORD') }}"
        spark.sql.catalog.minio_lake.warehouse: s3://commerce-lakehouse/warehouse
        spark.sql.catalog.minio_lake.io-impl: org.apache.iceberg.aws.s3.S3FileIO
        spark.sql.catalog.minio_lake.s3.endpoint: http://minio:9000
        spark.sql.catalog.minio_lake.s3.path-style-access: 'true'
        spark.sql.catalog.minio_lake.client.region: us-east-1
